source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mafeng-Bryant/Specs.git'

use_frameworks!

platform :ios, '6.0'

target 'MLoadingViewKit_Example' do
  pod 'MLoadingViewKit', :path => '../'

  target 'MLoadingViewKit_Tests' do
    inherit! :search_paths

    
  end
end
